### ISSUE TITLE
Historyファイルを正常に読み込めなかった際にエラーが出ずに強制終了する

### ISSUE THREAD

**Issue by tomosii** [IRSL-tut/robot_assembler_plugin#37]
存在しないconnecting-pointsが指定されている.roboasmファイルを読み込むと、エラーが出ずにChoreonoidが落ちてしまう。

何かしらのエラーメッセージが出るようにしたい。
（何が原因で落ちたのかがわかるようにしたい）

↓の例では仕様変更により、`bottom-side`という名前が存在しないため、読み込みに失敗する。
```
history: 
  - 
    initial-parts: true
    parts-name: XL-430_1_3
    parts-type: XL-430
  - 
    parent: XL-430_1_3
    parent-point: bottom-side
    parts-name: FR12_S102_S_1_4
    parts-point: side_connetct_point
    parts-type: FR12_S102_S
robot-info: 
  name: XL-430
```

```
[cnoid::MappingPtr cnoid::robot_assembler::parseInfo(const string&)] rd: /userdir/MyRobot.roboasm
[cnoid::MappingPtr cnoid::robot_assembler::parseInfo(const string&)]load: /userdir/MyRobot.roboasm
[cnoid::MappingPtr cnoid::robot_assembler::parseInfo(const string&)]doc: 1
[cnoid::MappingPtr cnoid::robot_assembler::parseInfo(const string&)]map: 0
[cnoid::MappingPtr cnoid::robot_assembler::parseInfo(const string&)]OK: /userdir/MyRobot.roboasm
// 強制終了
irsl@irsl-ThinkPad-W541:~/intern/irsl_docker$ 
```
